export let Cards = [
    {id:'1',
     name:'john',
     age:'27',
     place:'banglore'},
     {id:'2',
     name:'foo',
     age:'24',
     place:'banglore'},
     {id:'3',
     name:'john abraham',
     age:'29',
     place:'banglore'},
     {id:'4',
     name:'tom',
     age:'26',
     place:'banglore'},
     {id:'5',
     name:'james',
     age:'22',
     place:'banglore'},
     {id:'6',
     name:'crist',
     age:'25',
     place:'banglore'},
]